{
 "title": "TorqueMate Basic",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "session_id",
    "label": "Session",
    "query": "SELECT COALESCE(TO_CHAR(time AT TIME ZONE 'GMT+7', 'YYYY-MM-DD HH24:MI:SS'), '') AS __text, session_id AS __value\nFROM (\n    SELECT session_id, time, device_id,\n           ROW_NUMBER() over (PARTITION BY device_id, session_id ORDER BY time ASC) AS rn,\n           COUNT(*) over () AS total_count\n    FROM torque_data\n    WHERE device_id = '$device_id'\n) t\nWHERE rn = 1\nOR rn = total_count"
   },
   {
    "name": "device_id",
    "label": "Device",
    "query": "SELECT device_id FROM torque_data"
   }
  ]
 },
 "panels": [
  {
   "title": "Speed & RPM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ntime,\nobd_speed,\ngps_speed,\nobd_rpm\nFROM torque_data\nWHERE\n1=1\nAND session_id = '$session_id'\nAND device_id = '$device_id'"
    }
   ]
  },
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  gps_latitude[0] AS lat0,\n  gps_latitude[1] AS lat1,\n  gps_longitude[0] AS lng0,\n  gps_longitude[1] AS lng1,\n  session_id\nFROM torque_data\nWHERE\n1=1\nAND gps_latitude[0] <> 0\nAND gps_latitude[1] <> 0\nAND gps_longitude[0] <> 0\nAND gps_longitude[1] <> 0\nAND session_id = '$session_id'\nAND device_id = '$device_id'"
    }
   ]
  },
  {
   "title": "Coolant Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\ntime,\nobd_coolant_temperature\nFROM torque_data\nWHERE\n1=1\nAND session_id = '$session_id'\nAND device_id = '$device_id'"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\ntime,\nobd_battery_voltage\nFROM torque_data\nWHERE\n1=1\nAND session_id = '$session_id'\nAND device_id = '$device_id'"
    }
   ]
  }
 ]
}